### PR TITLE
Expected indentation of 2 spaces lint errors

### PR DESCRIPTION
**Pull request by acushlakoncept**
Adjusted the style.css file to fix the Expected indentation of 2 spaces lint errors

### CODE REVIEW

**Review by rammazzoti2000 — CHANGES_REQUESTED** [review]
### Hello @emmanuellekamwa  and @acushlakoncept , I'm Alex, your reviewer for this PR :man_astronaut: 

First of all, congrats in working on your second Microverse project :star2: 

I see you properly configured and fixed the linter errors :muscle: 
You also used proper html syntax and good css practices, congrats on that.
######

# Required Changes :building_construction: :pray: 
There are just a few small requirements I am asking you to make, which I am sure you can handle easily given the quality of your project.
- [ ] On the `a tags` I noticed you applied `:hover` pseudo code with a `font-weight` property. Please remove that since it kind of messes up the alignment when you hover on it.
- [ ] In the navbar the `a tag` must use same color as the original
### Original: 
image
### Clone: 
image
- [ ] The input tags must have round corners like in the original website
- [ ] The disclaimer text should match the context and style of the original page ([link to page](https://accounts.intuit.com/signup.html))
### Original:
image
### Clone: 
image
- [ ] The bottom section links should match the original ones
### Original:
image
### Clone:
image
### Tip :wink: :
The products row under the Intuit logo could be better aligned by changing from `display: inline-block` to `display: inline-flex` combined with `align-items: center`, also make sure to increase the size of the product images, they are quite tiny 
#
### <em>Kindly fix the REQUIRED issues and send another code review request.

Cheers and Happy coding! :clap: 

Code review by Alexandru Bangau

(Feel free to contact me on slack by the handle of alexandru if you have any additional question)</em>

**Review by rammazzoti2000 — CHANGES_REQUESTED** [review]
#### Status: Changes Required

**Comment by santiago-dev96** [comment]
# Pull Request under review by @santiago-rodrig (TSE)

**Comment by acushlakoncept** [comment]
> # Pull Request under review by @santiago-rodrig (TSE)

Ok thanks for the update, we're patiently waiting.

**Comment by santiago-rodrig** [comment]
## Changes required
Please, make sure that your PR looks professional as described [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/). Ask for another CRR (Code Review Request) after that. Have a nice day :wave:

I ask you this because the PR title is not descriptive, as well as the summary.

**Review by santiago-dev96 — CHANGES_REQUESTED** [review]
## Changes required
Please, make sure that your PR looks professional as described [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/). Ask for another CRR (Code Review Request) after that. Have a nice day :wave:.

I ask you this because the PR title is not descriptive, as well as the summary.

**Pull request closed without merging**
